homeInfoParams:
 Title: About
 Content: Hey, this is iniridwanul's blog. I like open diaries, but I don't like losing diary pages. Give me books, fruit, coffee, nice weather, and a little music. I will write an open diary.

ShowReadingTime: true
defaultTheme: dark
ShowCodeCopyButtons: true
showtoc: true

socialIcons:
  - name: "github"
    url: "https://github.com/iniridwanul"
  - name: "goodreads"
    url: "https://goodreads.com/iniridwanul"
  - name: "telegram"
    url: "https://t.me/about_iniridwanul"

label:
  text: "iniridwanul"
  icon: /logo/iniridwanul.png
  iconHeight: 40

assets:
  disableFingerprinting: true
  favicon: "/favicon/favicon.ico"
  favicon16x16: "/favicon/favicon-16x16.png"
  favicon32x32: "/favicon/favicon-32x32.png"
  apple_touch_icon: "/favicon/apple-touch-icon.png"