label:
  text: "iniridwanul"
  icon: /logo/iniridwanul.png
  iconHeight: 40

homeInfoParams:
    Title: "হ য ব র ল"
    Content: হ্যালো, [হ য ব র ল](/bn) ব্লগে আপনাকে স্বাগতম। নির্দিষ্ট কোনো বিষয় নিয়ে এই ব্লগ লেখা হয়নি। [সাইকোলজি](categories/সাইকোলজি), [ধর্ম চর্চা](categories/ধর্ম), [বই](categories/বুক-রিভিউ) এবং [অ্যানিমে রিভিউ](categories/অ্যানিমে-রিভিউ) নিয়ে জগাখিচুড়ির খোলা ডায়েরি তৈরির চেষ্টা করছি।

social: true
socialIcons:
  - name: "github"
    url: "https://github.com/iniridwanul"
  - name: "goodreads"
    url: "https://goodreads.com/iniridwanul"
  - name: "mastodon"
    url: "https://fosstodon.org/@iniridwanul"
  - name: "rss"
    url: "/bn/rss.xml"