homeInfoParams:
 Title: Notion
 Content: Give me books, fruits, coffee, fine weather, and a little music. I'll write an open diary.
ShowReadingTime: true
defaultTheme: dark
ShowCodeCopyButtons: true
showtoc: true

socialIcons:
  - name: "github"
    url: "https://github.com/iniridwanul"
  - name: "goodreads"
    url: "https://goodreads.com/iniridwanul"
  - name: "telegram"
    url: "https://t.me/about_iniridwanul"
  - name: "email"
    url: "mailto:iniridwanul@protonmail.com"