homeInfoParams:
 Title: অপ্রতিরোধ্য
 Content: অপ্রতিরোধ্যতার বন্ধনে আমৃত্যু সরল আমি।

defaultTheme: dark
ShowReadingTime: true
ShowCodeCopyButtons: true
showtoc: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowShareButtons: true

socialIcons:
  - name: "github"
    url: "https://github.com/iniridwanul"
  - name: "goodreads"
    url: "https://goodreads.com/iniridwanul"
  - name: "telegram"
    url: "https://t.me/about_iniridwanul"

label:
  text: "iniridwanul"
  icon: /logo/iniridwanul.png
  iconHeight: 40

assets:
  disableFingerprinting: true
  favicon: "/favicon/favicon.ico"
  favicon16x16: "/favicon/favicon-16x16.png"
  favicon32x32: "/favicon/favicon-32x32.png"
  apple_touch_icon: "/favicon/apple-touch-icon.png"